export const forMainHomePosts = [
  {
    id: 1,
    username: "Stoner Barbie",
    nickname: "@johnny",
    profilePic: "https://i.pravatar.cc/150?img=1",
    isVerified: true,
    postDate: "1H",
    content: "Loving the React ecosystem! 🚀",
    photo: "https://pbs.twimg.com/media/GiPqBdZXsAAVcOV?format=jpg&name=small", // Fotoğraf
    video: null, // Video
  },
  {
    id: 2,
    username: "Jane Smith",
    nickname: "@jane_smith",
    profilePic: "https://i.pravatar.cc/150?img=2",
    isVerified: false,
    postDate: "3H",
    content: "Just started learning Tailwind CSS. Any tips? 😊",
    photo: null, // Fotoğraf yok
    video: "https://www.youtube.com/embed/nOeJuoFs6sM?si=0Nq2rOpp1OVUeikO", // Video
  },
  {
    id: 3,
    username: "Alice Johnson",
    nickname: "@alicej",
    profilePic: "https://i.pravatar.cc/150?img=3",
    isVerified: true,
    postDate: "5H",
    content: "React + Tailwind = Perfect combo ❤️",
    photo: "https://avatars.mds.yandex.net/i?id=dec8208c2f1600677b329901fb82858bd110b6be-4234302-images-thumbs&n=13",
    video: "https://www.youtube.com/embed/nOeJuoFs6sM?si=0Nq2rOpp1OVUeikO",
  },
  {
    id: 4,
    username: "Bob Brown",
    nickname: "@bobby",
    profilePic: "https://i.pravatar.cc/150?img=4",
    isVerified: false,
    postDate: "7H",
    content: null,
    photo: "https://pbs.twimg.com/media/GjE_kK6bIAAWyor?format=jpg&name=large",
    video: null,
  },
  {
    id: 5,
    username: "Chris Wilson",
    nickname: "@chris_w",
    profilePic: "https://i.pravatar.cc/150?img=5",
    isVerified: true,
    postDate: "9H",
    content: "Working on a new open-source project. Stay tuned!",
    photo: null,
    video: 'https://www.youtube.com/embed/ho3wN1yICRQ?si=GFXOfg0vMr3Bg_40',
  },
  {
    id: 1,
    username: "Stoner Barbie",
    nickname: "@johnny",
    profilePic: "https://i.pravatar.cc/150?img=1",
    isVerified: true,
    postDate: "1H",
    content: "Loving the React ecosystem! 🚀",
    photo: "https://source.unsplash.com/featured/?technology",
    video: null,
  },  
  {
    id: 2,
    username: "Jane Smith",
    nickname: "@jane_smith",
    profilePic: "https://i.pravatar.cc/150?img=2",
    isVerified: false,
    postDate: "3H",
    content: "Just started learning Tailwind CSS. Any tips? 😊",
    photo: null,
    video: "https://www.youtube.com/embed/dQw4w9WgXcQ",
  },
  {
    id: 3,
    username: "Alice Johnson",
    nickname: "@alicej",
    profilePic: "https://i.pravatar.cc/150?img=3",
    isVerified: true,
    postDate: "5H",
    content: "React + Tailwind = Perfect combo ❤️",
    photo: "https://source.unsplash.com/featured/?coding",
    video: "https://www.youtube.com/embed/3JZ_D3ELwOQ",
  },
  {
    id: 4,
    username: "Bob Brown",
    nickname: "@bobby",
    profilePic: "https://i.pravatar.cc/150?img=4",
    isVerified: false,
    postDate: "7H",
    content: "Frontend development is so much fun! ✨",
    photo: "https://source.unsplash.com/featured/?developer",
    video: null,
  },
  {
    id: 5,
    username: "Chris Wilson",
    nickname: "@chris_w",
    profilePic: "https://i.pravatar.cc/150?img=5",
    isVerified: true,
    postDate: "9H",
    content: "Working on a new open-source project. Stay tuned! 🛠️",
    photo: null,
    video: "https://www.youtube.com/embed/I9ZlpVYB5U8",
  },
  {
    id: 6,
    username: "Tech Guru",
    nickname: "@techguru",
    profilePic: "https://i.pravatar.cc/150?img=6",
    isVerified: true,
    postDate: "10H",
    content: "Just 🚀",
    photo: "https://pbs.twimg.com/media/Gi_wpoyWwAAWbDM?format=jpg&name=900x900",
    video: null,
  },
  {
    id: 7,
    username: "Gaming Freak",
    nickname: "@game_master",
    profilePic: "https://i.pravatar.cc/150?img=7",
    isVerified: false,
    postDate: "12H",
    content: "Anyone up for a gaming night? 🎮🔥",
    photo: null,
    video: "https://www.youtube.com/embed/K4TOrB7at0Y",
  },
  {
    id: 8,
    username: "Fitness Freak",
    nickname: "@fit_life",
    profilePic: "https://i.pravatar.cc/150?img=8",
    isVerified: false,
    postDate: "15H",
    content: "It’s funny how you can never beāt them on a track. 💪🔥",
    photo: "https://pbs.twimg.com/media/GjHc7moWUAAhzRM?format=jpg&name=small",
    video: null,
  },
  {
    id: 9,
    username: "Vlogger",
    nickname: "@vloglife",
    profilePic: "https://i.pravatar.cc/150?img=9",
    isVerified: true,
    postDate: "18H",
    content: "New travel vlog just dropped! 🌍✨",
    photo: null,
    video: "https://www.youtube.com/embed/tgbNymZ7vqY",
  },
  {
    id: 10,
    username: "Foodie Lover",
    nickname: "@yumdelight",
    profilePic: "https://i.pravatar.cc/150?img=10",
    isVerified: false,
    postDate: "Feb 7",
    content: "I remind myself that me and everyone I knew had hair like this 🔥",
    photo: "https://pbs.twimg.com/media/GjEBxGvbIAAWiWC?format=jpg&name=medium",
    video: null,
  },  
];

